# Generated by Django 5.0.6 on 2024-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='group',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
