# Generated by Django 5.0.6 on 2024-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0003_foodtype_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='foodType',
            field=models.CharField(choices=[('KOR', '한식'), ('JPN', '일식'), ('WST', '양식'), ('CHN', '중식'), ('SNK', '분식'), ('OTH', '기타')], default='OTH', max_length=3),
        ),
    ]
