# Generated by Django 5.0.6 on 2024-07-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0004_alter_foodtype_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('memberAuth', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=100)),
                ('memberState', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('B', 'Banned')], default='A', max_length=1)),
            ],
        ),
    ]
