# Generated by Django 5.0.6 on 2024-07-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0006_member_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
        migrations.RemoveField(
            model_name='location',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
