# Generated by Django 5.0.6 on 2024-07-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0007_delete_foodtype_remove_location_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='MemberInfo',
        ),
    ]
