# Generated by Django 5.0.6 on 2024-07-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startService', '0011_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
